development:
  adapter: postgresql
  encoding: unicode
  database: articledb_dev
  pool: 5
  host: localhost
  username: krutik
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: articledb_test
  pool: 5
  username: krutik
  password: 123

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
